name: Run Python Script
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:       # Allows manual triggering
  push:
    branches: [ main ]     # Runs on pushes to main branch

jobs:
  execute-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute main.py
      run: python main.py

    - name: Verify completion
      run: echo "Script executed successfully at $(date)"
